name: Node.js CI - Calling reusable
on:
  workflow_dispatch

jobs:
  ci:
    name: run build process
    uses: DLActionableArena/shared-workflows/.github/workflows/sample.workflows.build-node.yml@main
