name: Node.js CI - Calling reusable
on:
  workflow_dispatch

jobs:
  ci:
    name: run build process
    uses: dlavalli/DLActionableArena/shared-workflows/tree/main/.github/workflows/sample.workflows.build-node.yml@main
